stats_app_index:
    path:     /
    defaults: { _controller: StatsAppChartsBundle:Stats:view }

stats_app_post:
    path:     /send
    defaults: { _controller: StatsAppChartsBundle:Stats:send }
    methods:  [POST]
