imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    #form:            ~
    #csrf_protection: ~
    #validation:      { enable_annotations: true }
    templating:
        engines: ['php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    #trusted_hosts:   ~
    #trusted_proxies: ~
    #session:
        # handler_id set to null will use default session handler from php.ini
        #handler_id:  ~
    fragments:       ~
    http_method_override: true

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# FOS Rest Bundle
fos_rest:
    format_listener:
        rules:
            - { path: '^/all', priorities: ['json'], prefer_extension: false }
            - { path: '^/data', priorities: ['json'], prefer_extension: false }
            - { path: '^/dbDriver', priorities: ['json'], prefer_extension: false }
            - { path: '^/dbVersion', priorities: ['json'], prefer_extension: false }
            - { path: '^/downloads', priorities: ['json'], prefer_extension: false }
            - { path: '^/installSource', priorities: ['json'], prefer_extension: false }
            - { path: '^/phpVersion', priorities: ['json'], prefer_extension: false }
            - { path: '^/serverOs', priorities: ['json'], prefer_extension: false }
            - { path: '^/version', priorities: ['json'], prefer_extension: false }
            - { path: '^/', methods: ['POST'], priorities: ['json'], prefer_extension: false }
            - { path: '^/', methods: ['GET'], priorities: ['html'], prefer_extension: false }
    param_fetcher_listener: true

parameters:
    supported_applications: ['Mautic']
    joomla_database:
        dbname:   "%joomla_dbname%"
        driver:   "%joomla_driver%"
        host:     "%joomla_host%"
        password: "%joomla_password%"
        user:     "%joomla_user%"
