imports:
    - { resource: parameters.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    assets:          ~
    #form:            ~
    #csrf_protection: ~
    #validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    #trusted_hosts:   ~
    #trusted_proxies: ~
    #session:
        # handler_id set to null will use default session handler from php.ini
        #handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            joomla:
                driver:   "%joomla_driver%"
                host:     "%joomla_host%"
                port:     "%joomla_port%"
                dbname:   "%joomla_dbname%"
                user:     "%joomla_user%"
                password: "%joomla_password%"
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# FOS Rest Bundle
fos_rest:
    format_listener:
        rules:
            - { path: '^/all', priorities: ['json'], prefer_extension: false }
            - { path: '^/data', priorities: ['json'], prefer_extension: false }
            - { path: '^/dbDriver', priorities: ['json'], prefer_extension: false }
            - { path: '^/dbVersion', priorities: ['json'], prefer_extension: false }
            - { path: '^/downloads', priorities: ['json'], prefer_extension: false }
            - { path: '^/installSource', priorities: ['json'], prefer_extension: false }
            - { path: '^/phpVersion', priorities: ['json'], prefer_extension: false }
            - { path: '^/serverOs', priorities: ['json'], prefer_extension: false }
            - { path: '^/version', priorities: ['json'], prefer_extension: false }
            - { path: '^/m3upgradejson', priorities: ['json'], prefer_extension: false }
            - { path: '^/m3upgrade', priorities: ['html'], prefer_extension: false }
            - { path: '^/', methods: ['POST'], priorities: ['json'], prefer_extension: false }
            - { path: '^/send', methods: ['POST'], priorities: ['json'], prefer_extension: false }
            - { path: '^/', methods: ['GET'], priorities: ['html'], prefer_extension: false }
    param_fetcher_listener: true

parameters:
    supported_applications: ['Mautic']

# Ekino New Relic Bundle
ekino_new_relic:
    enabled: false
    application_name: Mautic Statistics Application

