mautic_stats_index:
    type: rest
    resource: @MauticStatsBundle/Controller/StatsController.php

# Legacy GET handler
mautic_stats_data:
    path:     /data
    defaults: { _controller: MauticStatsBundle:Stats:data, _format: json }

# Legacy POST handler
mautic_stats_post:
    path:     /send
    defaults: { _controller: MauticStatsBundle:Stats:postData }
    methods:  [POST]
