mautic_stats_index:
    type: rest
    resource: "@MauticStatsBundle/Controller/StatsController.php"

# Legacy GET handler
mautic_stats_data:
    path:     /data
    defaults: { _controller: MauticStatsBundle:Stats:data, _format: json }

# Legacy POST handler
mautic_stats_post:
    path:     /send
    defaults: { _controller: MauticStatsBundle:Stats:postData }
    methods:  [POST]

# For collecting stats about M2 to M3 upgrade
mautic_3_upgrade_stats_post:
    path:     /mautic3upgrade/send
    defaults: { _controller: MauticStatsBundle:Stats:postMautic3UpgradeData }
    methods:  [POST]
