services:
    stats_app.factory:
        class: StatsAppBundle\Factory
        arguments: [@service_container]

    kernel.listener.stats_app_core_listener:
        class: StatsAppBundle\EventListener\CoreListener
        arguments: [@stats_app.factory]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
